apiVersion: v1
kind: ConfigMap
metadata:
  name: apex-link-config
  namespace: apex-link
data:
  NEXT_PUBLIC_SITE_DOMAIN: mostvaluable.link
  NEXT_PUBLIC_SITE_URL: https://mostvaluable.link
  INITIAL_PRICE_CENTS: "100"
  PRICE_INCREMENT_CENTS: "1"
  PRICE_DECAY_DAYS: "90"
